### ISSUE TITLE
Change starting hour in day view

### ISSUE THREAD

**Issue by awatson32** [SimformSolutionsPvtLtd/flutter_calendar_view#102]
Apologies if this has been requested previously, but is it possible to change the start time in day view from 1am to something else?
<img width="504" alt="Screen Shot 2022-08-31 at 9 33 38 AM" src="https://user-images.githubusercontent.com/7787006/187704991-4b5c8b6d-a1c6-4422-92b6-7c765cb81f1d.png">

**Comment by sir-adam-smith** [comment]
Would really love to see this functionality built in please!

**Comment by awatson32** [comment]
> #57
> 
> 

Just realized I was the one who initially asked this question and forgot 😅🤦🏻‍♀️
