### ISSUE TITLE
Is dark theme available for this widget?

### ISSUE THREAD

**Issue by rajendra-pragadareddi** [SimformSolutionsPvtLtd/flutter_calendar_view#103]
Hi ,
Is there a way to enable dark mode for this calender view ?

I was able to change theme for timeLineBuilder and background in Day View. My issue is specifically with dayTitleBuilder. How can I customize dayTitleBuilder.?

**Comment by ParthBaraiya** [comment]
Hello @rajendra-pragadareddi . This plugin does not support dark theme by default. As for your issue with dayTitleBuilder its a function that returns the `Widget` so, you can return any Widget from this function. This can be your customised widget for dark theme. 

Hope this solve your query. I'm closing this issue for now.
