### ISSUE TITLE
Does the calendar handle multiple day events? [Question]

### ISSUE THREAD

**Issue by alan-craftbrewerysolutions** [SimformSolutionsPvtLtd/flutter_calendar_view#12]

**Comment by ParthBaraiya** [comment]
@alan-craftbrewerysolutions As of now calendar by default does not handle multiple day events.

But If you have algorithm/code for multiple day event, you can provide it on initialisation of EventController.

ex,

``` dart
final controller = EventControler(
   eventFilter: (date, events){
      // Your code goes here. 
     // This function will return list of events that will be displayed on given date.
   },
);
```

We are planning to implement recurring events functionality in near future.

for now I am closing this issue. Feel free to reopen it if you need more info or it does not solve your query.

**Comment by alan-craftbrewerysolutions** [comment]
Thank you. I will test out that suggestion.
