### ISSUE TITLE
Month view scrolls too far to blank area

### ISSUE THREAD

**Issue by Elepert** [SimformSolutionsPvtLtd/flutter_calendar_view#123]
I'm adding MonthView() to my project and it scrolls to reveal the full month (which is fine) but it also scrolls past that and shows a blank area after that. I can't seem to get it to only scroll to show the month and nothing else (like in the example). 

https://user-images.githubusercontent.com/23346615/194167983-46b0a696-18e9-45c0-81ca-47aa9174e8f4.mov

My code structure is as follows:
```
DefaultTabController(
     child: Scaffold(
            ....
            body: TabBarView(....: [
                 ....
                 MonthView(),
            ])
    )
)
```

I've wrapped MonthView in a sizedbox or a container and it changes the size of the total widget but doesn't change the behavior. This is scrolling just the weeks, not the header (so not the entire MonthView widget) which makes me think this is a MonthView widget issue (or maybe I haven't formatted it correctly or something). Any insights would be appreciated!

**Comment by Elepert** [comment]
I've managed to recreate it with this code: 
```
class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(child: Container()),
        Expanded(
          child: Scaffold(
              // body: Text('Body'),
              body: MonthView()),
          // floatingActionButton: _bottomButtons(),
        ),
      ],
    );
  }
}
```
Specifically, adding another element to the row causes the behavior. If MonthView() is the only item in the row then it's fine.

**Comment by suraiyakawsar** [comment]
I am having the same issue, is there a way to resolve this asap?

**Comment by ParthBaraiya** [comment]
Hello guys, You need to provide width in this case.

> I've managed to recreate the issue with this code (which reflects my situation):
> 
> ```
> class Test extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Row(
>       children: [
>         Expanded(child: Container()),
>         Expanded(
>           child: Scaffold(
>               body: MonthView()),
>         ),
>       ],
>     );
>   }
> }
> ```
> 
> Specifically, adding another element to the row causes the behavior. If MonthView() is the only item in the row then it's fine.

In this demo you need to provide width of the `MonthView`. By default calendar view will take width from MediaQuery. That's why this problem is happening.  Considering the example, width should be `MediaQuery.of(context).size/2`. You can refer to this [demo app](https://simformsolutionspvtltd.github.io/flutter_calendar_view/) as well, it has the similar functionality.

**Comment by ParthBaraiya** [comment]
I'm closing this issue for now. Feel free to reopen this issue if given solution doesn't fix it.
