### ISSUE TITLE
Calendar not maintaining state

### ISSUE THREAD

**Issue by Raviteja11122** [SimformSolutionsPvtLtd/flutter_calendar_view#127]
I switched between views it not storing previous visited month/week/day every time it showing initial passed date.

**Comment by ParthBaraiya** [comment]
@Raviteja11122 Please share reproducible code.

**Comment by PRBaraiya** [comment]
Hi, @Raviteja11122  I'm closing this issue as we were not able to reproduce it. Feel free to reopen this issue if you are still facing it.
