### ISSUE TITLE
First event is duplicate in the calendar!!!!!

### ISSUE THREAD

**Issue by colosoderada** [SimformSolutionsPvtLtd/flutter_calendar_view#129]
First of all thank you for this calendar.
When I add a series of events to the calendar, the first one is duplicated, but the rest are working fine.

Some clue why you are doing it wrong when you paint it on the screen, because for the first event I only have 1 record to show and not two.

![image](https://user-images.githubusercontent.com/15679348/199484995-f23cc6e8-580f-4c4e-82a1-c7bd714f6616.png)
![image](https://user-images.githubusercontent.com/15679348/199485050-6763e7a2-1c19-48f6-8cfe-eeabd60b262c.png)
![image](https://user-images.githubusercontent.com/15679348/199487914-f547dd25-b82b-4a1b-bd8e-9a631b83f2f2.png)
![image](https://user-images.githubusercontent.com/15679348/199487933-ae72a7cf-c3be-4daa-900b-29e6c963e95c.png)
![image](https://user-images.githubusercontent.com/15679348/199487960-399d28cb-c37c-4597-8b94-d43d8a13e0c2.png)

calendario_view.dart (it is other file, it is not the main.dart file)

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'package:calendar_view/calendar_view.dart';
import 'package:portal_empleado/api/POJO/event.dart';
import 'package:portal_empleado/api/POJO/informe_empleado_responde.dart';
import 'package:portal_empleado/providers/informe_empleado_provider.dart';

class CalendarioView extends StatefulWidget {
  @override
  State<CalendarioView> createState() => _CalendarioViewState();
}

class _CalendarioViewState extends State<CalendarioView> {
  @override
  void dispose() {
    EventController<Event>().dispose();
    EventController().dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CalendarControllerProvider<Event>(
      controller: EventController(),
      child: Scaffold(
          body: MonthView(
              controller: EventController<Event>()..addAll(montarEventosCalendarios(context)), 
              minMonth: DateTime(2022),
              maxMonth: DateTime(2050),
              cellAspectRatio: 1,
              startDay: WeekDays.monday)),
    );
  }
}

List<CalendarEventData<Event>> montarEventosCalendarios(BuildContext context) {
  List<MisVacaciones> misVacacionesList = Provider.of<InformeEmpleadoProvider>(context).misVacacionesList;
  List<CalendarEventData<Event>> events = [];

  for (int i = 0; i < misVacacionesList.length; i++) {
    int yearIni = int.parse(misVacacionesList[i].fechaInicio!.substring(6, 10));
    int mesIni = int.parse(misVacacionesList[i].fechaInicio!.substring(3, 5));
    int diaIni = int.parse(misVacacionesList[i].fechaInicio!.substring(0, 2));
    int yearFin = int.parse(misVacacionesList[i].fechaFin!.substring(6, 10));
    int mesFin = int.parse(misVacacionesList[i].fechaFin!.substring(3, 5));
    int diaFin = int.parse(misVacacionesList[i].fechaFin!.substring(0, 2));

    events.add(CalendarEventData(
        date: DateTime(yearIni, mesIni, diaIni),
        endDate: DateTime(yearFin, mesFin, diaFin),
        title: misVacacionesList[i].atext!,
    ));
  }
  return events;
}

**Comment by ParthBaraiya** [comment]
I think this issue is fixed by PR #113 and will be available by next release.
