### ISSUE TITLE
How can I show the current date on DayView Calendar?

### ISSUE THREAD

**Issue by Phenoise** [SimformSolutionsPvtLtd/flutter_calendar_view#132]
I want to show the current date on DayView calendar by clicking buttons. Can anyone help me to solve this problem.
onPressed: () {
       code here>>>>>
                      }),

**Comment by ParthBaraiya** [comment]
@Phenoise  Please check [Use of Globalkeys](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/README.md#use-of-globalkey).
