### ISSUE TITLE
Calendar event data text colour

### ISSUE THREAD

**Issue by veritas144** [SimformSolutionsPvtLtd/flutter_calendar_view#147]
Hi, this is a great calendar package. Would it be possible to change the text colour of the calendar event data as you can do with the background colour?

**Comment by PRBaraiya** [comment]
@veritas144  Please confirm my understanding here, You want an option to set title color as we have `color` option for background color in `CalendarEventData` model. Am I Correct?

**Comment by veritas144** [comment]
Yes, that would be perfectOn 6 Dec 2022, at 14:52, Parth Baraiya ***@***.***> wrote:﻿
@veritas144  Please confirm my understanding here, You want an option to set title color as we have color option for background color in CalendarEventData model. Am I Correct?
