### ISSUE TITLE
Changing the time format on the left-hand side 

### ISSUE THREAD

**Issue by Saliim17** [SimformSolutionsPvtLtd/flutter_calendar_view#148]
Is there an option to change the format displayed for the hours in the weekly view? In my case I prefer 12:00 instead of 12 am. What I have found is that I can only modify the lines that indicate the hours and the current time but not the format displayed. 
`https://i.imgur.com/eHEnWnV.png`

**Comment by porum** [comment]
You can use `timeLineBuilder` to build your custom timeline.
https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/f11647b3257a149ede31f0fdd0e0b75c7864aaa9/lib/src/week_view/week_view.dart#L28

**Comment by PRBaraiya** [comment]
@Saliim17  I'm closing this issue as of now. Please reopen this issue if the answer given by @porum does not fix your issue.
