### ISSUE TITLE
Remove default padding under calendar in month view

### ISSUE THREAD

**Issue by RonTass** [SimformSolutionsPvtLtd/flutter_calendar_view#152]
Month view has a default padding at the bottom. Is it possible to remove it?

**Comment by faiyaz-shaikh** [comment]
@RonTass Can you please provide reproducible code.

**Comment by RonTass** [comment]
The issue is when I place the calendar in a column I have a padding at the bottom. I believe it's because of the SafeArea widget inside lib\src\month_view\month_view.dart. Once I set the Safe area bottom: false it's solving the issue. 
![image](https://user-images.githubusercontent.com/117252578/209882022-d4e3c85f-bbeb-471d-957b-9ffb85410d9b.png)

![image](https://user-images.githubusercontent.com/117252578/209882138-01c4244c-dea7-4547-a5d4-b6a5770836fe.png)

This is the code, I used the provided example, just added the container below the month view: 

`class _MonthViewPageDemoState extends State<MonthViewPageDemo> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        elevation: 8,
        onPressed: _addEvent,
      ),
      body: Container(
        height: MediaQuery.of(context).size.height - 100,
        width: MediaQuery.of(context).size.width,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            Expanded(
                child: Padding(
              padding: EdgeInsets.zero,
              child: MonthViewWidget(),
            )),
            Expanded(
              child: Container(
                color: Colors.black,
              ),
            )
          ],
        ),
      ),
    );
  }
`

**Comment by RonTass** [comment]
@faiyaz-shaikh

**Comment by RonTass** [comment]
Hi @faiyaz-shaikh , issue was solve, no need any further action.

**Comment by faiyaz-shaikh** [comment]
Hi @RonTass, Thanks for the code snippet. I am closing this issue.
