### ISSUE TITLE
Request to release latest master

### ISSUE THREAD

**Issue by Ayush-gupta-josh** [SimformSolutionsPvtLtd/flutter_calendar_view#154]
Hi,
As you have resolved many issues including [this](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/issues/144) issue which was resolved in [this PR](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/pull/145). I have verified the fix on the master branch, it is working fine now but it is not yet released in any version. Can you create a release for the current master branch so that we can use the latest fix?

**Comment by PRBaraiya** [comment]
We will release the new version of this plugin as soon as possible.
