### ISSUE TITLE
Q: How can I hide the calendar's view header?

### ISSUE THREAD

**Issue by 3g015st** [SimformSolutionsPvtLtd/flutter_calendar_view#156]
![image](https://user-images.githubusercontent.com/26760925/210131918-013ff865-d419-44e3-9b9e-2dbd7648c97c.png)
 
 I wanna hide the header for the date "1-1-2021", because I have a specific custom use case for only the view itself. I don't need the header? How can I do this?

**Comment by faiyaz-shaikh** [comment]
Hi @3g015st, You can provide dayTitleBuilder as Empty widget.
see code below :
`DayView<Event>(
      key: state,
      width: width,
      dayTitleBuilder: (date) => SizedBox()
    );`

**Comment by faiyaz-shaikh** [comment]
I am closing this issue for now. Feel free to open if not fixed.
