### ISSUE TITLE
Changing UI of Monthly View Calendar

### ISSUE THREAD

**Issue by MateuszPeryt** [SimformSolutionsPvtLtd/flutter_calendar_view#158]
Is there a way to change the colors of the monthly view? The DayView and WeekView have "backgroundColor" property, but there is nothing like this for MonthlyView. I tried using cell builder but i had further difficulties since there is no documentation about it. Is there any simple way to do this? I would greatly appreciate it.

DayView (what I want to achieve):
![image](https://user-images.githubusercontent.com/62548076/210151782-7f348504-15b8-4959-b6f9-35a16fd54bc1.png)

MonthView(I want to change, for example, the background colour and text colour):
![image](https://user-images.githubusercontent.com/62548076/210151795-4a851f06-9a04-4512-aa1e-e0009f5f730f.png)

**Comment by faiyaz-shaikh** [comment]
Hi @MateuszPeryt, You can provide colours by using public class **FilledCell** to **cellBuilder**,
See below code : 
```
MonthView<Event>(
      key: state,
      width: width,
      cellBuilder: (date, events, isInMonth, shouldHighlight) => FilledCell(
        date: date,
        events: events,
        backgroundColor: Colors.green,
      ),
    );
```

**Comment by faiyaz-shaikh** [comment]
I am closing this issue for now. Feel free to open if not fixed.
