### ISSUE TITLE
Change the days of the week to Portuguese 

### ISSUE THREAD

**Issue by RafaelVasques** [SimformSolutionsPvtLtd/flutter_calendar_view#159]
How can I change the days of the week to Portuguese?

**Comment by faiyaz-shaikh** [comment]
Hi @RafaelVasques, Do you mean title of week day M, T, W... ? For that you can use weekDayStringBuilder.

**Comment by faiyaz-shaikh** [comment]
I am closing this issue for now. Feel free to open if not fixed.

**Comment by stephenhauck** [comment]
I am trying to use this on the week_view and it seems it does not work.
It works in the month view properly....
Any advice ?
