### ISSUE TITLE
Scroll to index/liveTime

### ISSUE THREAD

**Issue by Andrauss** [SimformSolutionsPvtLtd/flutter_calendar_view#16]
Hi, i've ben testing your library on my project.
I didn't found any way to scroll to an event index or liveTimeIndicator, is this possible?

**Comment by angshu** [comment]
looking for same. Any clue?

**Comment by AlexandreMaul** [comment]
Hello,
My pull request #40 has just been merged. You can wait for the next release or point to the master branch.

By using the "scrollOffset" parameter on the DayView and WeekView widgets, it's possible to set scroll.

I hope this will meet your need.

**Comment by PRBaraiya** [comment]
> Hello, My pull request #40 has just been merged. You can wait for the next release or point to the master branch.
> 
> By using the "scrollOffset" parameter on the DayView and WeekView widgets, it's possible to set scroll.
> 
> I hope this will meet your need.

This fix is released on pub.dev. So, I'm closing this issue for now.
