### ISSUE TITLE
On EventTap not working in month view

### ISSUE THREAD

**Issue by loreminekarthik** [SimformSolutionsPvtLtd/flutter_calendar_view#160]
In month view on event tap is not working in web as we tested

**Comment by PRBaraiya** [comment]
@loreminekarthik Can you please share reproducible code.

**Comment by loreminekarthik** [comment]
Hi @PRBaraiya , here is the code below used:
`MonthView<Event>(
      key: widget.state,
      width: widget.width,
      borderColor:   Colors.blue,
      borderSize: 1,
      cellBuilder: _customCellBuilder,
      weekDayBuilder: _customWeekDayBuilder,
      headerStyle: const HeaderStyle(headerTextStyle: TextStyle(color: Colors.white),leftIconVisible: true,
          leftIcon: Icon(Icons.keyboard_arrow_left_outlined, color: Colors.white ,size: 20,),
          rightIconVisible: true,
          rightIcon:   Icon(Icons.keyboard_arrow_right_outlined, color: Colors.white ,size: 20,),
         
          decoration:  BoxDecoration(color:   Colors.blue)),
      cellAspectRatio: 1,
      onCellTap: (List<CalendarEventData<Event>> events, DateTime date){
        print("Events length - ${events.length}");
        // int taskId =  int.parse(events[0].description);
      },
      onEventTap: (CalendarEventData<Event> event, DateTime date){
        Console.log("print","working");
        print("Event tapped - ");
      },
      onPageChange: (DateTime dateTime, int index){
     
        if(widget._swipeNotifier != null){
          widget._swipeNotifier!.onSwipeDetected(dateTime, CalendarType.MONTH);
        }
      },
    )`

**Comment by PRBaraiya** [comment]
Hi, @loreminekarthik  Here you are providing your custom cellBuilder. that's why it's not working. It's also mentioned [here](https://pub.dev/documentation/calendar_view/latest/calendar_view/MonthView/onEventTap.html).
