### ISSUE TITLE
Recurring Event Weekly

### ISSUE THREAD

**Issue by bitdelve** [SimformSolutionsPvtLtd/flutter_calendar_view#163]
Is it possible to create an event that recures weekly between two dates? I.E> Start Date is 1/7/2023 End Date is 2/7/2023 and recures at the same time each Friday between those two dates?

**Comment by PRBaraiya** [comment]
Hi, @bitdelve Unfortunately this package does not provide that functionality for now. But we are planning to add it soon.

**Comment by vinz-mehra** [comment]
Any updates on this?

**Comment by PRBaraiya** [comment]
Closing this as the PR are merged. Create new issues if this is not the change you need.
