### ISSUE TITLE
Failed to add event in DayView

### ISSUE THREAD

**Issue by ingmferrer** [SimformSolutionsPvtLtd/flutter_calendar_view#171]
flutter: 1. Start time or end time might be null
flutter: 2. endTime occurs before or at the same time as startTime.

`{date: 2023-01-14 09:00:00.000, startTime: 2023-01-14 09:00:00.000, endTime: 2023-01-15 02:00:00.000, event: DealModel{), endDate: 2023-01-15 02:00:00.000}`

This happens when an event spans two day. Does the calendar support two-day events?

Thanks.

**Comment by PRBaraiya** [comment]
No, @ingmferrer calendar_view does not support it currently. But we are planning to add it ASAP.

**Comment by ingmferrer** [comment]
I can help, let me know.

**Comment by PRBaraiya** [comment]
Sure @ingmferrer, Feel free to raise the PR if you want.
