### ISSUE TITLE
Stop month view scrolling

### ISSUE THREAD

**Issue by TassTesting** [SimformSolutionsPvtLtd/flutter_calendar_view#175]
Hi,

Even after giving the calendar month view fixed hight, it still scrollable. 
Is it possible to add the SingleChildScrollView widget option to set the physics parameter to NeverScrollableScrollPhysics().

Thanks

**Comment by RonTass** [comment]
With different devices sometime the calendar hight change, and make it scrollable which causing issue when it's placed inside another scrollable list.

**Comment by MaxGallegos** [comment]
You find a workaround for this?
