### ISSUE TITLE
Add ability to not show the header for the DayView

### ISSUE THREAD

**Issue by Jack423** [SimformSolutionsPvtLtd/flutter_calendar_view#183]
When you are showing a schedule for something specific to a single day, the header at the top of the DayView becomes redundant. We currently have the ability to edit the header, but not remove it or disable it completely.

**Comment by faiyaz-shaikh** [comment]
Hi @Jack423 If you want to remove the header then you can pass the Empty widget to the dayTitleBuilder
```
DayView<Event>(
      key: state,
      width: width,
      dayTitleBuilder: (date) => SizedBox(),
    );
```

**Comment by Jack423** [comment]
Perfect, thank you
