### ISSUE TITLE
How to add recurring appointments until the specified date in the Flutter Calendar

### ISSUE THREAD

**Issue by amjad07** [SimformSolutionsPvtLtd/flutter_calendar_view#188]
is there a workaround that allow recurring appointments functionality using this flutter_calendar_view??

**Comment by faiyaz-shaikh** [comment]
Hi @amjad07, Currently this package does not provide that functionality for now. But we are planning to add it soon. And also we are open to any code contribution. so if you would like to create a PR with the functionality then we are happy to have that.
Thanks.

**Comment by faiyaz-shaikh** [comment]
Closing this issue because of similar issue is open #163
