### ISSUE TITLE
Support for custom colours in the default implementation of Month view's current day

### ISSUE THREAD

**Issue by Vidxyz** [SimformSolutionsPvtLtd/flutter_calendar_view#189]
I noticed that the default `cellBuilder` implementation for `MonthView` does not have the ability to configure the circle background colour for the current date circle as displayed in the view.

Digging further, I see that the `FilledCell<T>` widget actually provides an option to configure the color `this.highlightColor = Colors.blue`

```
  const FilledCell({
    Key? key,
    required this.date,
    required this.events,
    this.isInMonth = false,
    this.shouldHighlight = false,
    this.backgroundColor = Colors.blue,
    this.highlightColor = Colors.blue,
    this.onTileTap,
    this.tileColor = Colors.blue,
    this.highlightRadius = 11,
    this.titleColor = Constants.black,
    this.highlightedTitleColor = Constants.white,
    this.dateStringBuilder,
  }) : super(key: key);
```

However, the calling method does not parameterize this option and thus only the default is made available to the `MonthView` parent widget

```
  /// Default cell builder. Used when [widget.cellBuilder] is null
  Widget _defaultCellBuilder(
      date, List<CalendarEventData<T>> events, isToday, isInMonth) {
    return FilledCell<T>(
      date: date,
      shouldHighlight: isToday,
      backgroundColor: isInMonth ? Constants.white : Constants.offWhite,
      events: events,
      onTileTap: widget.onEventTap,
      dateStringBuilder: widget.dateStringBuilder,
    );
  }
```

Can this be incorporated as a feature? If this is not in the works I could attempt a PR to realize this functionality

Thanks! Apologies if this feature is already present and I just wasn't able to find it!

**Comment by faiyaz-shaikh** [comment]
Hi @Vidxyz, If I understand correctly you want to provide configuration to the cell builder. As FilledCell Widget is a public class you can return to the cellBuilder directly. Please see the below code.
```
MonthView<Event>(
      key: state,
      width: width,
      cellBuilder: (date, events, isToday, isInMonth) {
        // Provide your custom widget
        return FilledCell(
          date: date,
          shouldHighlight: isToday,
          events: events,
          highlightColor: Colors.green,
        );
      },
    );
```

**Comment by Vidxyz** [comment]
Thanks, this is perfect. I didn't realize `FilledCell` was public!
