### ISSUE TITLE
displayBorder in WeekDayTile in month_view_components does not work correctly

### ISSUE THREAD

**Issue by kaidrumm** [SimformSolutionsPvtLtd/flutter_calendar_view#191]
We created a month view and set displayBorder to false, but the border still shows.

Solution: Copy the logic from showBorder in _MonthPageBuilder in month_view.dart.

**Comment by kaidrumm** [comment]
I can fix this if you assign it to me

**Comment by faiyaz-shaikh** [comment]
Hi @kaidrumm, Thanks for creating an issue. I assigned it to you.
