### ISSUE TITLE
Responsive behavior (web)

### ISSUE THREAD

**Issue by serkanok1983** [SimformSolutionsPvtLtd/flutter_calendar_view#194]
Web home page smoothly resizes responsibly to decreasing page width and finally adapts ui, the left part remains. But when you size up back the ui does not return to its default, it remains as it was modified to fit in small width.

**Comment by PRBaraiya** [comment]
@serkanok1983  Can you please share the code base that can reproduce this issue?

**Comment by ParthBaraiya** [comment]
Closing this for now as there are not enough information to reproduce this issue. If this issue is still there in latest build, feel free to reopen this issue or create a new one with reproducible steps or a video that demonstrate the issue.
