### ISSUE TITLE
How to change datepicker style

### ISSUE THREAD

**Issue by YellowKitKat** [SimformSolutionsPvtLtd/flutter_calendar_view#214]
Is it possible to change the style of the datepicker that shows when you click on the header? 
When in dark mode the datepicker is almost unreadable in my app:
![image](https://user-images.githubusercontent.com/130477896/231680857-19847b9d-87ec-4226-892e-8ba1cb68a183.png)

I saw that it is possible to give a custom title bar via the `dayTitleBuilder` param, but I would like to keep the default title bar and only change the style of the datepicker.

**Comment by ParthBaraiya** [comment]
Hi @YellowKitKat , We are using the date picker that flutter provides so, only way to update the theme of the date picker is to pass `dayTitleBuilder`. And if you want default style, calendar_view exposes `DayPageHeader` widget that is being used as default title for day view. You can return this widget from `dayTitleBuilder`.

Hope this helps.

I'm closing this issue for now. Feel free to reopen the issue if there is any confusion.
