### ISSUE TITLE
Custom equality checking in CalendarEventData 

### ISSUE THREAD

**Issue by zombie6888** [SimformSolutionsPvtLtd/flutter_calendar_view#215]
Is it possible to extend CalendarEventData somehow ? I want to use custom equality checking, by event id and not by date, time, description or title

**Comment by zombie6888** [comment]
Finally, i figured out how it works. You can add equality checking to your custom event and use  generic type CalendarEventData<CustomEvent>. But there is another problem: if you adding event to event controller which is already exists, controller will do nothing (the _addEvent method has return statement for this case). But i want to replace old one with new one. My use case is that other users can update event (change time, tittle or other  props) and i want to see changes in real time (we are using websocket connection).

**Comment by ParthBaraiya** [comment]
@zombie6888  Thanks for sharing this. We will look into this and update ASAP.

**Comment by ParthBaraiya** [comment]
Closing this as Main issue for Custom equality check is figured.

Can continue discussion for update event feature in this issue #125 .
