### ISSUE TITLE
There is an issue with the daily view  layout display

### ISSUE THREAD

**Issue by sunyanduo** [SimformSolutionsPvtLtd/flutter_calendar_view#219]
Create 3 events:
12:00-12:30
12:31-13:01
12:00-13:00
Then check display in day view

there is a overlap in these events

![Screenshot 2023-05-07 000731](https://user-images.githubusercontent.com/36261739/236641263-2fefb155-852e-4e7b-9a9b-90b79eaf32f2.png)

**Comment by DhavalRKansara** [comment]
Hi @sunyanduo This issue has been resolved in PR #245.
