### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Flavio-Vieirastack** [SimformSolutionsPvtLtd/flutter_calendar_view#22]
on my calendar i just need these little arrows to select the weeks, i would like to remove the date information from the center and change the color from blue to white, could you explain to me how to do this? I tried but I couldn't
![Sem título](https://user-images.githubusercontent.com/85948951/142627260-9a620689-c2de-4433-ba9e-1bfaa6b0c4e3.png)

i try this but i recive this error

```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
PageController.page cannot be accessed before a PageView is built with it.
'package:flutter/src/widgets/page_view.dart':
package:flutter/…/widgets/page_view.dart:1
Failed assertion: line 172 pos 7: 'positions.isNotEmpty'
```

`_AssertionError ('package:flutter/src/widgets/page_view.dart': Failed assertion: line 172 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.)`

try

```
weekPageHeaderBuilder: (DateTime startDate, DateTime endDate) {
        return Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            IconButton(
              onPressed: ()=> controller.pageController.previousPage(duration: const Duration(milliseconds: 300), 
curve: Curves.linear),
              icon: const Icon(Icons.arrow_back_ios, size: 15,),
            ),
            IconButton(
              onPressed: (){},
              icon: const Icon(Icons.arrow_forward_ios, size: 15,),
            ),
          ],
        );
      },
```
my page controller and previous page method

```
late PageController pageController = PageController();

  void previousPage({Duration? duration, Curve? curve}) {
    pageController.previousPage(
      duration: duration ?? const Duration(milliseconds: 300),
      curve: curve ?? Curves.linear,
    );
  }
```

**Comment by ParthBaraiya** [comment]
You don't have to create a page controller separately to change page. WeekViewState provides methods to do that.

In your code create a `GlobalKey<WeekViewState>` and assign it to you `WeekView` widget.

ex,

```dart
final key = GlobalKey<WeekViewState>();

Widget build(BuildContext context){
    return WeekView(
        key: key,
        ...,
    );
}
```

Then use that key to change page on tap. In onPressed property of IconButton use `key.currentState.nextPage()` or `key.currentState.previousPage()` to change the page.

For more info please visit: 
    https://pub.dev/packages/calendar_view#use-of-globalkey
    https://pub.dev/documentation/calendar_view/latest/calendar_view/WeekViewState-class.html

**Comment by Flavio-Vieirastack** [comment]
Thnx for help my friend
