### ISSUE TITLE
Full Day Event 

### ISSUE THREAD

**Issue by Ensonberg** [SimformSolutionsPvtLtd/flutter_calendar_view#229]
I am reading events such as public holidays and birthday from user local calendar , what parameters i need to add to for it to make the event controller recognise it as a full data event. by default it is showing as normal event in the weekview 

var calendarEventsResult = await _deviceCalendarPlugin.retrieveEvents(
        calendar.id,
        RetrieveEventsParams(startDate: startDate, endDate: endDate));
    _calendarEvents = calendarEventsResult.data ?? [];

    await Future.forEach(_calendarEvents, (item) async {
      final event = CalendarEventData<eve.Event>(
        color: Palette.hugRed,
        date: DateTime(
          item.start!.year,
          item.start!.month,
          item.start!.day,
          item.start!.hour,
        ),
        startTime: DateTime(item.start!.year, item.start!.month, -1,
            item.start!.hour > item.end!.hour ? 1 : item.start!.hour),
        endTime: DateTime(
          item.end!.add(Duration(days: 1)).year,
          item.end!.add(Duration(days: 1)).month,
          -1,
          item.start!.hour > item.end!.hour ? 24 : item.end!.hour,
        ),
        //  startTime: item.start,
        description: item.description ?? "",
        event: eve.Event(title: "data"),
        title: item.title!,
      );
    
      events.add(event);
    }).then((value) {
      ref.watch(coreProvider).addEvents(events);

      print(events.length);
    });

**Comment by Yohannfra** [comment]
If someone has the solution I'm also interested
