### ISSUE TITLE
how to get events to align instead of overlap

### ISSUE THREAD

**Issue by Dieterbe** [SimformSolutionsPvtLtd/flutter_calendar_view#232]
Hi! If you look af Friday the 9th, you can see a 'Dat-AM' and 'Dat-PM' event. the PM event follows the AM.
The AM event has this endTime and endDate:
```
DateTime(dat.year, dat.month, dat.day, 12, 12, 12);
```
The PM event, i needed to experiment with different values, and observed that any startTime and date, up to `DateTime(dat.year, dat.month, dat.day, 12, 12, 59);` results in the "overlapping" render. Whereas using 12:13:00 works to get the properly aligned rendering.
i would expect as soon as an event starts after a previous event, it should not overlap, but it seems you need a certain amount of seconds of space to make this work properly? is there a trick to make this work elegantly?

## overlapping (bad):
![Screenshot_20230607-191102](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/20774/e42bc6b1-ba28-45db-a298-15cc4ec855ff)
## aligned (good)
![Screenshot_20230607-191541](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/20774/e8bd66c2-2263-4eee-947b-d1bc2080fab0)

**Comment by Dieterbe** [comment]
is the trick that it has to cross into a new minute? because if i use 12:12:59 end, and 12:13:00 start, then it renders properly again..

**Comment by jaiminrana05** [comment]
Hi @Dieterbe, our latest release 1.0.4 has fixed this issue. Please give it a look.

**Comment by alex-dokienko** [comment]
I also get same issue on 1.0.4 on daily view (same as on week view)

**Comment by PRBaraiya** [comment]
Closing this issue. Please refer issue #290  for latest update.
