### ISSUE TITLE
[ Can't customize "EventTile" for MonthView ]

### ISSUE THREAD

**Issue by Gobmichet** [SimformSolutionsPvtLtd/flutter_calendar_view#234]
Hi,
Thanks for the job !

Got a problem to customize the "EventTile" for monthView.
I did manage to do it on DayView && WeekView but can't find a builder that renders the "rounded" event to customize ?

**> What is the equivalent of EventTileBuilder for MonthView please !?**

Thanks in advance !

**Comment by PRBaraiya** [comment]
Closing this issue for now. Please raise a new one if required.

**Comment by henycave** [comment]
I wanted to show some info when a tile is hovered but there is no eventTileBuilder in month view, even FilledCell and  CircularCell do not have it. Do you know how I can do that?
