### ISSUE TITLE
Wrong event width in day view and weekview

### ISSUE THREAD

**Issue by Matt0550** [SimformSolutionsPvtLtd/flutter_calendar_view#238]
Hi, I can't figure out how I can fix this. My eventful view turns out to be so unreadable. How can I put the width of each event to maximum? same thing the height?

DayView:
![Screenshot_1688323753](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/65899974/0ba85ad3-a012-4ca8-a82b-cfbbffe78b51)
cc4b40669)

WeekView
![Screenshot_1688323856](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/65899974/a728565b-1448-449c-a606-e78f16e359c7)

My code:
```
return CalendarControllerProvider(
            controller: eventController,
            child: DayView(
              // weekDays: const [
              //   WeekDays.monday,
              //   WeekDays.tuesday,
              //   WeekDays.wednesday,
              //   WeekDays.thursday,
              //   WeekDays.friday,
              //   WeekDays.saturday,
              // ],
              timeLineBuilder: (date) {
                final timeLineString =
                    DateFormat("HH:mm", "it_IT").format(date);
                return Transform.translate(
                  offset: const Offset(0, -7.5),
                  child: Padding(
                    padding: const EdgeInsets.only(right: 7.0),
                    child: Text(
                      timeLineString,
                      textAlign: TextAlign.right,
                      style: const TextStyle(
                        fontSize: 15.0,
                      ),
                    ),
                  ),
                );
              },
              heightPerMinute: 1,
              showLiveTimeLineInAllDays: false,
            ),
```

**Comment by DhavalRKansara** [comment]
Hi @Matt0550,

Sorry for the delayed reply. Could you please check if the issue persists in the latest release of flutter_calendar_view? If it does, it would be helpful if you could share the code along with the events you are trying to add for the Day and Month views.

Thank you!
