### ISSUE TITLE
Min and Max Hours

### ISSUE THREAD

**Issue by david-melodica** [SimformSolutionsPvtLtd/flutter_calendar_view#240]
Hello, 

I am really enjoying working with this control!

However, it seems like there is no option to set min and max hours in a day like how I can set min and max days.

I also cannot seem to figure out a workaround for this, please help

Best
![image](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/123624574/6b11be44-6918-44d8-b3b0-350cb4c0b446)

David

**Comment by jaiminrana05** [comment]
Hi,@ david-melodica Can you please elaborate more on what is the issue?

**Comment by david-melodica** [comment]
> Hi,@ david-melodica Can you please elaborate more on what is the issue?

Hello, sure, I would like to set min and max hours in a dayview so that it does not show all hours of the day.

for example I only want to see the time slots from 8am to 9pm, not from midnight to midnight

Is that clear enough?

**Comment by Mael-Kehl** [comment]
Hey, I'm having the same problem that @david-melodica, it would definitely be a great idea to integrate that.

**Comment by david-melodica** [comment]
> Hey, I'm having the same problem than @david-melodica, it would definitely be a great idea to integrate that.

Hey Mael, I didnt get much of a response so I ended up making my own calendar control

**Comment by Mael-Kehl** [comment]
Because I need this feature to be implemented on the project I'm working on, I've begin to code a solution including a "startHour" parameter to WeekView and DayView constructors. I'll create a PR once work is done so you guys can take a look and why not add it to the next version.

**Comment by jaiminrana05** [comment]
Hello, @Mael-Kehl We are grateful for any PRs submitted by developers.
