### ISSUE TITLE
Is it possible to display only 3 consecutive days of the week ?

### ISSUE THREAD

**Issue by Mael-Kehl** [SimformSolutionsPvtLtd/flutter_calendar_view#246]
Hello, I'm currently developping an app using the calendar and I'm wondering if it is possible to display only three days in weekView, dynamically. 
For instance, I would like to display thursday, friday and monday, but when I'm specifying those days in the "weekDays" parameter, it displays me Monday, Thursday and Fridray, in this order. 
Is there a solution ?

**Comment by PRBaraiya** [comment]
Hi @Mael-Kehl , Not sure if this is the solution for the problem you are facing, But can you try providing,

`startDay: WeekDay.thursday`
`weekDays: [list of days]`

**Comment by Mael-Kehl** [comment]
> Hi @Mael-Kehl , Not sure if this is the solution for the problem you are facing, But can you try providing,
> 
> `startDay: WeekDay.thursday` `weekDays: [list of days]`

Hi, thanks for your answer, I wasn't using the startDay properly.
