### ISSUE TITLE
Exception caused by "Null check operator used on a null value" when event doesn't have a startDate

### ISSUE THREAD

**Issue by MiroslavBlagoev** [SimformSolutionsPvtLtd/flutter_calendar_view#258]
**1. Steps to reproduce:**
      **1a)** in the `onCellTap: (events, date)` add an event without startDate like this:
    
```dart
    // saves the event data in the `event` variable
    final CalendarEventData<Object?> event = CalendarEventData(
            title: Random().nextInt(100).toString(),
            date: date,
            startTime: null, // this line can be omitted, its here just for acknowledgement
          );

         // adds the event to the controller
          eventController.add(event);
```

**1b)** click the cell twice -> see the error.

**2. Conclusion: There won't be an error on the first click. After the second click, though, you will see it.**

The error is caused by:

```dart
  void addEventInSortedManner(CalendarEventData event) {
    var addIndex = -1;
    for (var i = 0; i < this.length; i++) {
      if (event.startTime!.compareTo(this[i].startTime!) <= 0) {
        addIndex = i;
        break;
      }
    }

    if (addIndex > -1) {
      this.insert(addIndex, event);
    } else {
      this.add(event);
    }
  }
```

called in  `_addEvent()` function. The error is in the line ` if (event.startTime!.compareTo(this[i].startTime!) <= 0)`
and is caused by the fact that `startTime` is _by default_ **null**, so we are calling `null!` which is guaranteed to throw an exception.

**3. Solution:**
**3a)** Either make `startTime` **required** of the type **DateTime**
**3b)** Or use the null aware operator (`?`) in order to prevent the comparison from executing when the value of `startTime` is **null**.

**Comment by apurva010** [comment]
Closing this issue as it got fixed in latest version.
