### ISSUE TITLE
When adding full-day events to WeekView, the date is ignored

### ISSUE THREAD

**Issue by Yogi1043** [SimformSolutionsPvtLtd/flutter_calendar_view#259]
When adding full-day events to WeekView, the date is ignored and they are grouped to the left. 
Is there something wrong with the event configuration?
![rapture_20230831111238](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/143672469/03769a65-3e31-4662-87f0-db21e61a9a40)

List<CalendarEventData<CalendarEvent>> events = [
          CalendarEventData(
            date: DateTime(2023, 9, 1),
            endDate: DateTime(2023, 9, 2),
            startTime: DateTime(2023, 9, 1),
            endTime: DateTime(2023, 9, 2),
            event: CalendarEvent(title: "Joe's Birthday"),
            title: "11Project meeting",
            description: "Today is project meeting.",
            color: Colors.purple,
          ),
          CalendarEventData(
            date: DateTime(2023, 8, 30),
            endDate: DateTime(2023, 8, 30),
            startTime: DateTime(2023, 8, 30,0),
            endTime: DateTime(2023, 8, 30,1),
            event: CalendarEvent(title: "11Joe's Birthday"),
            title: "11Project meeting",
            description: "11Today is project meeting.",
            color: Colors.red,
          ),
          CalendarEventData(
            date: DateTime(2023, 9, 1),
            endDate: DateTime(2023, 9, 2),
            startTime: DateTime(2023, 9, 1),
            endTime: DateTime(2023, 9, 2),
            event: CalendarEvent(title: "W4edding anniversary"),
            color: Colors.blue,
            title: "Wedding anniversary",
            description: "Attend uncle's wedding anniversary.",
          ),
];

Thanks

**Comment by MartimTSilva** [comment]
Any solution?
