### ISSUE TITLE
Is there support for locale?

### ISSUE THREAD

**Issue by fabiohxcx** [SimformSolutionsPvtLtd/flutter_calendar_view#26]
Hi, I liked a lot this package, but I wasn't able to find a way to change locale.
is there any planning to support?

Thanks

**Comment by AliceLespagnol** [comment]
Hello @fabiohxcx we have the same problem. Have you finally found a solution to change locale ?

Thanks

**Comment by fabiohxcx** [comment]
Hi Alice,

I needed to implement `timeLineBuilder`, `eventTileBuilder`, etc. 

Like this:
```

 timeLineBuilder: (date) => Transform.translate(
        offset: Offset(0, -7.5),
        child: Padding(
          padding: const EdgeInsets.only(right: 7.0),
          child: Text(
            "${((date.hour - 1)) + 1} h",
            textAlign: TextAlign.right,
            style: TextStyle(fontSize: 15.0),
          ),
        ),
      ),
```

```
weekDayBuilder: (day) => Container(
        alignment: Alignment.center,
        margin: EdgeInsets.zero,
        padding: EdgeInsets.symmetric(vertical: 10.0),
        decoration: BoxDecoration(
          border: Border.all(
            color: Color(0xffdddddd),
            width: 0.5,
          ),
        ),
        child: Text(
          weekTitles[day],
          style: TextStyle(
            fontSize: 17,
            color: AppColors.black,
          ),
        ),
      ),
```

I used the default implementations as a base.

But if the owner allows us, I think we can create a Pull Request in order to implemente locale as a new feature.

**Comment by vatsaltanna-simformsolutions** [comment]
Hello, We would love to have your contribution to this repository. so feel free to create a PR for any bug fix or an enhancement.

Thanks

**Comment by b-scharbau** [comment]
Added PR #36

**Comment by faiyaz-shaikh** [comment]
Added in 1.0.1 PR #107 #36
