### ISSUE TITLE
Cannot add event to calendar

### ISSUE THREAD

**Issue by andreaaas** [SimformSolutionsPvtLtd/flutter_calendar_view#261]
Hi, i'm I'm trying to add new event to calendar, the code is the following:
```
CalendarControllerProvider.of(context).controller.add(
          CalendarEventData(
            date: DateTime(2023,9,14),
            endDate: DateTime(2023,9,15),
            startTime: DateTime(2023,9,15),
            endTime: DateTime(2023,9,15),
            event: "test", title: 'Test',
          )
        );
```
this not work, i not see error, but on the calendar there is no event

**Comment by PRBaraiya** [comment]
Hello @andreaaas , Can you share what view are you using? If it's day / week view, you need to provide time in startTime and endTime. Else it won't work.
