### ISSUE TITLE
Not able to run the app because of WidgetsBinding error in dayview

### ISSUE THREAD

**Issue by SachinTanpure** [SimformSolutionsPvtLtd/flutter_calendar_view#262]
^
../../FlutterHome/flutter/.pub-cache/hosted/pub.dartlang.org/calendar_view-1.0.4/lib/src/day_view/day_view.dart:327:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../FlutterHome/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/Shree/Documents/FlutterHome/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/Shree/Documents/FlutterHome/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1

Below is my Flutter Doctor output
flutter doctor -v 
[✓] Flutter (Channel unknown, 2.10.4, on macOS 13.1 22C65 darwin-arm, locale en-IN)
    • Flutter version 2.10.4 at /Users/Shree/Documents/FlutterHome/flutter
    • Upstream repository unknown
    • Framework revision c860cba910 (1 year, 5 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/Shree/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/Shree/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • SM M515F (mobile) • RZ8N902ZZEL • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 116.0.5845.140

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by apurva010** [comment]
Closing this issue as it got fixed in latest version.
