### ISSUE TITLE
15 minutes grid option is not there.

### ISSUE THREAD

**Issue by prabinlamsal19** [SimformSolutionsPvtLtd/flutter_calendar_view#270]
There is no option for showing a 15 minute grid. There is an option called minuteSlotSize which takes MinuteSlotSize.minutes15 but   no 15 minute grid line is shown.

**Comment by prabinlamsal19** [comment]
Hey, I have fixed the issue and also added the 30 minute grid lines and 15 minutes grid lines in the WeekView for using it in my project. Shall I send a PR here??

**Comment by ParthBaraiya** [comment]
Sure @prabinlamsal19 , Any contribution is welcomed.
