### ISSUE TITLE
Can't change background color weekDayStringBuilder in MonthView, havn't properties like this

### ISSUE THREAD

**Issue by ThangStar** [SimformSolutionsPvtLtd/flutter_calendar_view#273]
![image](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/52882277/400e7cdd-c890-4fa0-a659-a0f97ed56b9e)

**Comment by ravilsimform** [comment]
Hi @ThangStar you can change background color inside **MonthView** using **weekDayBuilder** inside you can use **WeekDayTile**. Inside weekDayBuilder you can also use **weekDayStringBuilder** and customised your **weekday** strings.

```
weekDayBuilder: (int value) {
        return WeekDayTile(
          dayIndex: value,
          backgroundColor: value > 4 ? Colors.red : Colors.blue,
          // weekDayStringBuilder: (int value) {
          //   if (value == 6) {
          //     return 'SUN';
          //   }
          //   return '';
          // },
        );
      }
```

<img width="536" alt="Screenshot 2024-02-16 at 4 54 54 PM" src="https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/97508406/995d12f7-d3b9-4dd1-8b44-4a1b16e7d83c">
