### ISSUE TITLE
Events automatically removed when the view is refreshed or rebuild. using setState or Getx controller

### ISSUE THREAD

**Issue by abdulrehman192** [SimformSolutionsPvtLtd/flutter_calendar_view#288]
All the events added in the EventController automatically removed when I attempt to refresh the screen with any state manager.

Also When the width of screen the events deleted automatically.

**Comment by PRBaraiya** [comment]
@abdulrehman192 , Can you share the code that will help us reproduce this issue?

**Comment by ParthBaraiya** [comment]
Closing this issue because of no response.
