### ISSUE TITLE
Issue with time duplicate range 00

### ISSUE THREAD

**Issue by huynguyen96419** [SimformSolutionsPvtLtd/flutter_calendar_view#289]
Currently, for the time range from 12:00 - 15:00 and 15:00-16:00, since there is a clash at 15:00, the interface is split into two sides as shown in the image. Is there a way to move the item with the time range of 15:00-16:00 closer to the left side when duplicate 15:00?
![Screenshot 2023-11-13 at 4 42 58 PM](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/127708425/b898b46b-9f10-4494-bcc4-55fcbe2ec36b)

**Comment by ParthBaraiya** [comment]
This issue has been fixed in master branch. We've added a parameter in eventArrangers to deside whether to arrange those events side by side or one by one as column.
