### ISSUE TITLE
Is there a way to stack events and not offset them ?

### ISSUE THREAD

**Issue by stephenhauck** [SimformSolutionsPvtLtd/flutter_calendar_view#290]
We want to stack these and not offset them unless the times overlap ...
<img width="385" alt="image" src="https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/12648793/fa29e2a3-fb73-4a1d-a467-b8c746ed7a52">

**Comment by Eretik33-176** [comment]
I am currently having the same problem with this package. My first guess would be to try and make it so that event are built with an end date 1 min or 1 second before the actual date. I don't know how to do that in the EventBuilder yet.

**Comment by stephenhauck** [comment]
@Eretik33-176  that's not really a legit "fix"

**Comment by stephenhauck** [comment]
anyone ?

**Comment by stephenhauck** [comment]
OK will I did some digging and in the MergeEventArranger code seems to be where it decides if they overlap and simply having the same start and end time seems to be a reason to overlap so it slides them .....

**Comment by PRBaraiya** [comment]
@stephenhauck That is the default behavior of that arranger. We will add a flag in those arrangers to decide whether these kinds of events should stack or offset.

**Comment by PRBaraiya** [comment]
We will need that flags in `MergeEventArranger` and `SideEventArranger`.

**Comment by stephenhauck** [comment]
When it's building the layout it throws errors if you use midnight as a start or end time too ...
I/flutter ( 9310): Failed to add event because of one of the given reasons:
I/flutter ( 9310): 1. Start time or end time might be null
I/flutter ( 9310): 2. endTime occurs before or at the same time as startTime.
I/flutter ( 9310): Event data:
I/flutter ( 9310): {date: 2023-10-11 23:00:00.000, startTime: 2023-10-11 23:00:00.000, endTime: 2023-10-12 00:00:00.000, event: Instance of 'CalendarItemInfo', title: 11 PM Appointment, description: , endDate: 2023-10-12 00:00:00.000}

**Comment by PRBaraiya** [comment]
@stephenhauck That's because for start and end time, event arrangers will not consider the date i.e, year, month and day. So, here, start time and end time is same 00:00:00. That's why it's giving the error.

Please refer issue #293  for more updates.

As for the work around, you can set end time to, `2023-10-11 23:59:00.000`

**Comment by DonnyDevIT** [comment]
**I'm here because I would like to reopen the issue.**

As you can see on this screenshot, the events are arranged and all looks good.
<img width="2016" alt="Screenshot 2024-08-01 alle 11 55 46" src="https://github.com/user-attachments/assets/330fad14-4921-4885-8bb6-686dead8d7d2">

But on this screenshot, where have a big (yellow) event on the left, the arranger does not work properly. I expect that the dark ones on the right are not offsetted
<img width="2016" alt="Screenshot 2024-08-01 alle 11 54 48" src="https://github.com/user-attachments/assets/bd79d91b-a722-4e9d-9663-268522d009a2">


@ParthBaraiya @PRBaraiya **_Can we please reopen this and take a look?_**

**Comment by PRBaraiya** [comment]
@DonnyDevIT Not sure if this will work, but can you try providing eventArranger argument. Here is an example,

```dart
DayView(
    eventArranger: SideEventArranger(
        includeEdges: true,
    ),
);
```

**Comment by DonnyDevIT** [comment]
Hi @PRBaraiya No does not work, **it works fine until I put the big yellow on the left**, maybe something that package developers does not had in mind

**Comment by PRBaraiya** [comment]
Need to reproduce this issue with exact durations as above events.

**Comment by DonnyDevIT** [comment]
Ok, tell me if you work on something or need something

**Comment by DonnyDevIT** [comment]
Any news?

**Comment by DonnyDevIT** [comment]
Sorry, any updates? im getting some trouble :) @PRBaraiya

**Comment by DonnyDevIT** [comment]
Okay thanks! I will wait with no reply then :) @PRBaraiya

**Comment by ParthBaraiya** [comment]
Hi @DonnyDevIT I tried to replicate your scenario. Does below screenshot shows the output you are expecting? I tried to replicate the event data from the screen shot you shared.
![Screenshot 2024-09-14 005535](https://github.com/user-attachments/assets/f2aae532-301c-42d1-a9ea-fd789ef96e46)

**Comment by ParthBaraiya** [comment]
> Hi @DonnyDevIT I tried to replicate your scenario. Does below screenshot shows the output you are expecting? I tried to replicate the event data from the screen shot you shared. ![Screenshot 2024-09-14 005535](https://private-user-images.githubusercontent.com/36261739/367423400-f2aae532-301c-42d1-a9ea-fd789ef96e46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDQxODEsIm5iZiI6MTcyNjMwMzg4MSwicGF0aCI6Ii8zNjI2MTczOS8zNjc0MjM0MDAtZjJhYWU1MzItMzAxYy00MmQxLWE5ZWEtZmQ3ODllZjk2ZTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4NTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNGMzZDlkZmRmMWIyYjliMWEzZGUxZDJkOGM4ZjE4MWU5ZjQxNDZkMTI3MDI4MDFkZDE3OWY1NjAyNzhmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o5--6k5uoolhtnM1psSB54dbpYxevueTvErr1z8bGq0)

@DonnyDevIT Please ignore the UI of the tile. I'm just trying to show the arrangement of the tiles.

**Comment by DonnyDevIT** [comment]
@ParthBaraiya Yes, your screenshot is right, should be like this
