### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by rmpt** [SimformSolutionsPvtLtd/flutter_calendar_view#291]
Is it possible to change the language of the calendar?

**Comment by PRBaraiya** [comment]
Hello @rmpt , You can set the builders to change the language of the calendar. Like, `cellBuilder` in `MonthView`, `eventTileBuilder` in `DayView` etc. Calendar view exposes some of the widgets that it uses internally to show the UI. You can use those Widgets with builders to change the language of the calendar.

Closing this issue for now. Please raise a new issue if this doesn't answer your question.

**Comment by rmpt** [comment]
And what about the left side of the day view? Can I translate the time?

![image](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/16465379/923a9e5d-ae25-4949-b9ab-8a63daed200a)

**Comment by PRBaraiya** [comment]
Yes, there is a custom builder for that as well.
