### ISSUE TITLE
Can i change start time and end time in DayView?

### ISSUE THREAD

**Issue by huynguyen96419** [SimformSolutionsPvtLtd/flutter_calendar_view#298]
![Screenshot 2023-11-27 at 11 44 13 AM](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/127708425/a723adc9-6504-45a6-8142-e49f6091fc4d)
By the default, the time range of the DayView from 00:00 -> 24:00, so can i change to 08:00 -> 20:00?
Thank you so much!

**Comment by laguerreuy** [comment]
Same question! 
Awesome widget by the way

**Comment by Adm94** [comment]
yes you with the startHour option but there is no endHour option
```
DayView<Event>(
 startHour: 8,
)
```

**Comment by apurva010** [comment]
Close this issue as it is duplicate of #240.
