### ISSUE TITLE
How to add a custom line on the timeline of the network as shown below:

### ISSUE THREAD

**Issue by LIUPING789** [SimformSolutionsPvtLtd/flutter_calendar_view#300]
Hi Thank you for contributing a good lib. I encountered a problem. How do I add a specified line to the timeline at the network as shown below:
![企业微信20231220-174944](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/8344456/57c4dd7e-fa5f-4fe0-807f-caee44975018)
 

how do i need to do it,  thanks.

**Comment by ParthBaraiya** [comment]
HI @LIUPING789 right now this package does not support this functionality.

I'm closing this and marking this as potential-enhancement as we might take this once we've fixed all major issues and enhancements.
