### ISSUE TITLE
Hide header in Week View

### ISSUE THREAD

**Issue by hhelmric** [SimformSolutionsPvtLtd/flutter_calendar_view#303]
How can I hide the header on the WeekView? The documentation and previous issues seem to imply that we can set dayTitleBuilder to null, but this property doesn't exist on the WeekView.

**Comment by laguerreuy** [comment]
Set both back and forward buttons to false and in the header text style set font height to 0

**Comment by ravilsimform** [comment]
Hi @hhelmric For hiding header on weekView. we can use **weekPageHeaderBuilder** property and return with **SizedBox.shrink()**. Its hide the weekView header.
```
weekPageHeaderBuilder: (_,__) {
return SizedBox.shrink();
},
```
