### ISSUE TITLE
How to add a custom widget at the current time when clicking on onDateTap in the weekly view?

### ISSUE THREAD

**Issue by LIUPING789** [SimformSolutionsPvtLtd/flutter_calendar_view#304]
Hi~

How to add a custom widget at the current time when clicking on onDateTap in the weekly view?

thanks~

**Comment by ParthBaraiya** [comment]
Hi @LIUPING789  What do you mean by adding custom widget? Can you give me an example?

**Comment by ParthBaraiya** [comment]
Closing this as there is no response.
