### ISSUE TITLE
Weekday border dose not change with monthview show border false

### ISSUE THREAD

**Issue by saad-01** [SimformSolutionsPvtLtd/flutter_calendar_view#306]
month view file show include this:
Widget _defaultWeekDayBuilder(int index) {
    return WeekDayTile(
      dayIndex: index,
      weekDayStringBuilder: widget.weekDayStringBuilder,
      displayBorder: widget.showBorder, // this line should be added there
    );
  }

**Comment by apurva010** [comment]
You can make custom `weekDayBuilder` in that you can access `displayBorder` field which does the same thing.
