### ISSUE TITLE
Min/max hour for week and day view

### ISSUE THREAD

**Issue by rmpt** [SimformSolutionsPvtLtd/flutter_calendar_view#311]
Sometimes it doesn't make sense to show the entire day hours (from 0 to 23).
O property like minHour and maxHour would make sense so the hours shown in these views can be adjusted according the need of the user.

**Comment by AppsaraYoga** [comment]
There is a PR for that but it appears it won't be merged because the developer has not yet resolved the conflicts and it has been a long time

https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/pull/254

**Comment by rmpt** [comment]
I'll try to give it a look later. Maybe I can clone the changes and add endHour too. Thanks for the reply

**Comment by masalha-alaa** [comment]
Very much needed

**Comment by rmpt** [comment]
if someone can have a look at the PR:
https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/pull/319
