### ISSUE TITLE
Remove all event from Calendar

### ISSUE THREAD

**Issue by VivekVithlani** [SimformSolutionsPvtLtd/flutter_calendar_view#313]
Hello,

I want to remove all events (remove all events from the calendar), but I did not find any function or method to remove all events from the whole calendar.

I found only `removeEvnet` method.

Right now, I am using below approach to remove all events

`for (var event in eventController.events) {
      eventController.remove(event);  
}`

Kindly provide a better solution if one exists.

Thank you,
Vivek Vithalani.

**Comment by ahmetakil** [comment]
`eventController.removeWhere((_) => true);`

This worked well for me

**Comment by mac066** [comment]
Is there any update??

**Comment by ParthBaraiya** [comment]
Closing this for now as a solution already exists.
