### ISSUE TITLE
How to hide date in column header?

### ISSUE THREAD

**Issue by farrukhnajmi** [SimformSolutionsPvtLtd/flutter_calendar_view#315]
In WeekView, I  would like to hide the dates in column header (see attached image). How can I do that?
![Screenshot from 2024-01-31 19-49-32](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/1976247/033e5cff-db1f-4dc5-92d9-ea99e71fb1f1)

**Comment by AppsaraYoga** [comment]
You can do that by returning a SizedBox in the weekDayBuilder or by setting the weekTitleHeight to 0.

![image](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/156524738/bf4b8030-531b-4af0-a260-3d3431dcc383)

**Comment by AppsaraYoga** [comment]
or like this
![image](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/156524738/25e61857-e92c-443b-aa3d-4f0a4ed354b1)

**Comment by farrukhnajmi** [comment]
The second example is just what I was looking for. Thank you.
