### ISSUE TITLE
Apply filter for full day's events

### ISSUE THREAD

**Issue by Vov4yk** [SimformSolutionsPvtLtd/flutter_calendar_view#320]
Hello. Looks like filter is ignored for full day's events

![Screenshot 2024-02-06 at 15 42 39](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/6408642/247f368b-27d8-400d-bb50-8cadde896292)

**Comment by apurva010** [comment]
Closing this issue as issue got fixed in #307.
