### ISSUE TITLE
Why does DayView.onEventTap return a list?

### ISSUE THREAD

**Issue by masalha-alaa** [SimformSolutionsPvtLtd/flutter_calendar_view#322]
Right now when an event is tapped in DayView, onEventTap is called with a list although it seems like there's always one item in the list. I would expect a single event to be passed (the event that was tapped).

**Comment by ParthBaraiya** [comment]
@masalha-alaa In `DayView` and `WeekView` we are providing types of eventArrangers which defines how overlapping events should be displayed. One of the event arranger is `MergeEventArranger` which merges the overlapping events into a single event. So, for that merged event, `onEventTap` will have list of all the events that's been merged.

**Comment by ParthBaraiya** [comment]
Closing this issue for now. Please raise a new issue if required.
