### ISSUE TITLE
WeekView events onEventTap does not get triggered for the current week. 

### ISSUE THREAD

**Issue by ahmetakil** [SimformSolutionsPvtLtd/flutter_calendar_view#329]
When using the last version 1.1.0 and using a WeekView, when i add an event to this week's calendar so for instance yesterday or tomorrow, 

onEventTap does not get called, but when i move the event to either next weeks calendar (For instance adding Duration of 6 days)
or to a previous weeks calendar (Removing duration of 7 days)

Then the onEventTap works as expected. 

This issue does not happen if I rollback to version 1.0.4 

DayView works fine as well so this seems to only effect the WeekView.

**Comment by Lingeshwaran78** [comment]
have you found the solution?

**Comment by ahmetakil** [comment]
I'm using the version  `calendar_view: 1.0.4` which works as expected

**Comment by MaharGhazanfar** [comment]
> When using the last version 1.1.0 and using a WeekView, when i add an event to this week's calendar so for instance yesterday or tomorrow,
> 
> onEventTap does not get called, but when i move the event to either next weeks calendar (For instance adding Duration of 6 days) or to a previous weeks calendar (Removing duration of 7 days)
> 
> Then the onEventTap works as expected.
> 
> This issue does not happen if I rollback to version 1.0.4
> 
> DayView works fine as well so this seems to only effect the WeekView.

This is because of Live time line indicator as if we set it for all days than  event click alse not work for next week or previous week event like in current week. i have tried on previous version but the problem still exist.

**Comment by ahmetakil** [comment]
There is a new commit on master branch that seems to fix this, I'm using that now that it's working as expected

Note as of now that is not live on pub.dev so you would need to reference the git repo directly

**Comment by apurva010** [comment]
Closing this issue as issue got fixed in #335.
