### ISSUE TITLE
onDateTap not triggered in current week view

### ISSUE THREAD

**Issue by jt274** [SimformSolutionsPvtLtd/flutter_calendar_view#332]
This issue has occurred after updating to `1.1.0`.

When tapping on a date/time in `WeekView`, the `onDateTap` callback should be fired, but it is not if the week view shown is of the current week. If the calendar week is swiped to a previous week or future week, the callback works.

`onDateTap` is not trigged in this code example if in the current week. For example, today is March 12, and it will not work **only** if the calendar is showing the week of March 11-17.

```
WeekView(
  onDateTap: (time) {
    print('***TAPPED: $time');
  },
)
```

This may be related to #329

**Comment by apurva010** [comment]
Closing this issue as issue got fixed in #335.
