### ISSUE TITLE
Change firstDayOfTheWeek on calendar day/month/week picker

### ISSUE THREAD

**Issue by dimityrivanov** [SimformSolutionsPvtLtd/flutter_calendar_view#337]
Hey currently there is no way to change the firstDayOfTheWeek when you click on the header of the calendar even when I try to override the locale it seems I am unable to change it to start from Monday.

is it possible in future build to apply locale to the calendar based on user locale as param ?

**Comment by apurva010** [comment]
Hi @dimityrivanov, Could you please specify what things you need to change? If you need to change firstDayOfTheWeek on calendar then you can go ahead with `startDay` field in week and month view.

**Comment by apurva010** [comment]
I am closing this issue for now, feel free to reopen if this is not the case.
