### ISSUE TITLE
More customization without creating our own builder

### ISSUE THREAD

**Issue by Ionys320** [SimformSolutionsPvtLtd/flutter_calendar_view#34]
Hi!
Would it be possible to change some settings of the MonthView without using headerBuilder?
For example, change Icons colors, header's background color. (as you can see, all the changes would be focused on colors, because it's recurrent to customize them without having the need to change everything).

Thanks for this great package!

**Comment by philitell** [comment]
Yes please - this would be great!!
Especially for changing the background color of the header.

**Comment by awatson32** [comment]
Came here to see if this was possible. Great package!

**Comment by PRBaraiya** [comment]
Hello guys, Thanks for bringing this issue and all of your complements. We will add this feature as soon as possible.

Not sure If you guys already know this or not but, if you want the same page header as default one with color changes you can use widgets provided by plugin. There are three widgets that you can use with headerBuilder,
- `MonthPageHeader`
-  `DayPageHeader` 
- `WeekPageHeader`

These widgets will provide you color customizations for background and action icons.

But yes, in future we will add those customizations in `MonthView`, `DayView` and `WeekView` so, that you don't have to provide headerBuilder at all.

**Comment by tiger5226** [comment]
@PRBaraiya Not sure if you noticed but `WeekPageHeader` is the only one missing the background color. Looks like an oversight and should be a quick fix to add the line in without causing any compatibility issues. Thoughts?

**Comment by loreminekarthik** [comment]
We are also facing the same issue in the calendar view (day, week). Where we cannot change the header bg color and text color.

**Comment by faiyaz-shaikh** [comment]
Added in 1.0.1 #122
