### ISSUE TITLE
OnTap

### ISSUE THREAD

**Issue by lnsiqueira** [SimformSolutionsPvtLtd/flutter_calendar_view#35]
Hi, How to get OnTap event appointment details?

Tks. Luciano

**Comment by alex-moovago** [comment]
Hi, For DayView and WeekView it's onEventTap and onCellTap for MonthView.

You can do this to take info from your event.
```dart
DayView<Event>(
// Other params
onEventTap: (events, date) {
// events is the event you taped
// date is the date of the card
}),
```

I hope it helps you.

**Comment by lnsiqueira** [comment]
Thank you a lot!

Have a nice day.
