### ISSUE TITLE
is there a way to show a 24 hour format for the weekView?

### ISSUE THREAD

**Issue by mklepaczko** [SimformSolutionsPvtLtd/flutter_calendar_view#370]
is there a way to show a 24 hour format for the weekView?

**Comment by ravilsimform** [comment]
@mklepaczko you can use timeLineStringBuilder inside weekview.

`  timeLineStringBuilder: (date, {secondaryDate}) {
         return '${date.hour}:${date.minute}';
      },`
      
      
<img width="580" alt="Screenshot 2024-05-23 at 5 13 38 PM" src="https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/97508406/371e85c0-1f25-4989-a46a-a5dfe14cb79c">

**Comment by mklepaczko** [comment]
Works like a charm, thanks a lot for this quick answer!

Could be in the readMe.
