### ISSUE TITLE
Type is not a subtype of type

### ISSUE THREAD

**Issue by Geparder** [SimformSolutionsPvtLtd/flutter_calendar_view#380]
Bug in Flutter 3.22.2:

`
The following _TypeError was thrown building InternalWeekViewPage<...>-[<'60.02024-06-17 00:00:00.000'>](state: _InternalWeekViewPageState<Object?>#8c681):
type '(List<CalendarEventData<...>>, DateTime) => void' is not a subtype of type '((List<CalendarEventData<Object?>>, DateTime) => void)?'`

on onEventTap

need:

```
  @override
  State<InternalWeekViewPage> createState() => _InternalWeekViewPageState();
```

to 

```
  @override
  State<InternalWeekViewPage> createState() => _InternalWeekViewPageState<T>();
```

and all same files

**Comment by Geparder** [comment]
fix:

```
---
 lib/src/day_view/_internal_day_view_page.dart   | 2 +-
 lib/src/week_view/_internal_week_view_page.dart | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/lib/src/day_view/_internal_day_view_page.dart b/lib/src/day_view/_internal_day_view_page.dart
index d46be38..d608629 100644
--- a/lib/src/day_view/_internal_day_view_page.dart
+++ b/lib/src/day_view/_internal_day_view_page.dart
@@ -176,7 +176,7 @@ class InternalDayViewPage<T extends Object?> extends StatefulWidget {
   }) : super(key: key);
 
   @override
-  _InternalDayViewPageState<T> createState() => _InternalDayViewPageState();
+  _InternalDayViewPageState<T> createState() => _InternalDayViewPageState<T>();
 }
 
 class _InternalDayViewPageState<T extends Object?>
diff --git a/lib/src/week_view/_internal_week_view_page.dart b/lib/src/week_view/_internal_week_view_page.dart
index 2603e89..ff73a61 100644
--- a/lib/src/week_view/_internal_week_view_page.dart
+++ b/lib/src/week_view/_internal_week_view_page.dart
@@ -211,7 +211,7 @@ class InternalWeekViewPage<T extends Object?> extends StatefulWidget {
   }) : super(key: key);
 
   @override
-  _InternalWeekViewPageState<T> createState() => _InternalWeekViewPageState();
+  _InternalWeekViewPageState<T> createState() => _InternalWeekViewPageState<T>();
 }
 
 class _InternalWeekViewPageState<T extends Object?>
-- 
```

![Снимок экрана 2024-06-17 в 14 09 25](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/9677796/874ca30b-811a-4fc6-9475-a76509e28ffe)
![Снимок экрана 2024-06-17 в 14 09 29](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/9677796/34909d6e-8f95-4705-8415-0a556cef10b0)

**Comment by dkobia** [comment]
@Geparder It looks like this has been resolved by e3c127b9a5f92208c0ef3cbe9ba2664d64261c0d

**Comment by Geparder** [comment]
Not certainly in that way. The error keeps appearing. You just need to initialize the object instance as Generic.

Need:

_InternalWeekViewPageState<T> createState() => _InternalWeekViewPageState**<T>**();

**Comment by ProfessorX737** [comment]
Yes please fix this. Quite crucial part of the package. just need the `<T>`
