### ISSUE TITLE
`startHour` in `WeekView` Causing Incorrect Display of Quarter Hours

### ISSUE THREAD

**Issue by MDeLuise** [SimformSolutionsPvtLtd/flutter_calendar_view#387]
Hi all

#### Description
I am experiencing an issue with the `WeekView` widget where the quarter hours are not displayed correctly when the `startHour` property is set.

#### Code
Here is the relevant portion of my code:

```dart
WeekView(
  controller: widget.env.eventController,
  onPageChange: (date, page) async => _fetchEvents(date),
  showLiveTimeLineInAllDays: true,
  minDay: DateTime(2024),
  heightPerMinute: 1.3,
  showHalfHours: true,
  showQuarterHours: true,
  eventArranger: const SideEventArranger(),
  onEventTap: (events, date) => print(events),
  onEventDoubleTap: (events, date) => print(events),
  onDateLongPress: (date) => print(date),
  startDay: WeekDays.monday,
  //startHour: 7,
  hourIndicatorSettings: HourIndicatorSettings(),
  endHour: 20,
  showVerticalLines: true,
  fullDayHeaderTitle: 'All day',
  fullDayHeaderTextConfig: const FullDayHeaderTextConfig(
    textAlign: TextAlign.center,
    textOverflow: TextOverflow.ellipsis,
    maxLines: 2,
  ),
  keepScrollOffset: true,
)
```

#### Problem
The quarter-hour indicators are displayed correctly when the `startHour` property is not set. However, when I set `startHour: 7`, the quarter hours are not displayed correctly. They appear to start from 12:15 instead of 7:00.

#### Visualization
I have attached an image to illustrate the issue:
<img width="1418" alt="Screenshot 2024-07-05 at 18 37 57" src="https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/assets/66636702/76c89f93-d0b6-413e-9fcc-77a8bdb5efa5">

#### Steps to Reproduce
1. Use the `WeekView` widget.
2. Set the `startHour` property to any value (e.g., `startHour: 7`).
3. Enable `showQuarterHours: true`.

#### Expected Behavior
The quarter-hour indicators should start displaying from the set `startHour` (e.g., 7:00) and not from 12:15.

#### Environment
- Flutter version: 3.19.2
- calendar_view version: 1.2.0

**Comment by DonnyDevIT** [comment]
Same to me

**Comment by MDeLuise** [comment]
Really thanks, I'll try that

**Comment by DonnyDevIT** [comment]
Any updates to when this will be fixed?

**Comment by DonnyDevIT** [comment]
Nice!
