### ISSUE TITLE
Is there a way to customize the Grid in WeekView?

### ISSUE THREAD

**Issue by Basha0** [SimformSolutionsPvtLtd/flutter_calendar_view#397]
Hi,
I would like to customize the Gridview 
<img width="336" alt="Bildschirmfoto 2024-08-12 um 15 42 37" src="https://github.com/user-attachments/assets/25a0306d-a585-4d05-b08d-98e1e7e0e9ed">
I would like to have a card grid view something like below.
<img width="329" alt="Bildschirmfoto 2024-08-12 um 15 43 13" src="https://github.com/user-attachments/assets/236a57c3-acda-4ee5-8d40-6cb35cb28955">

**Comment by ParthBaraiya** [comment]
Hi @Basha0 Right now, this package does not support this functionality. And we are not planning to add this in near future either. 

I'm closing this issue and adding potential-enhancement for this issue as we might add this functionality once all the majority bugs / features are completed.
