### ISSUE TITLE
Start time issue in DayView

### ISSUE THREAD

**Issue by RameshGavs** [SimformSolutionsPvtLtd/flutter_calendar_view#425]
if i set 24 hrs time start time - 0 and endTime set as 24 ...but actual timeline list showing starting from 00:15 to 23:45 

ex : i need to show start time 00:00 and endTime 24:00

**Comment by shubham-jitiya-simform** [comment]
This issue appears to be similar to issue #267. Therefore, it will be closed as a duplicate. Please refer to the open PR #377 for more details.
If you believe this issue is different from the existing one, please provide a detailed description of the problem.
