### ISSUE TITLE
inconsistent 'onTap' api.

### ISSUE THREAD

**Issue by bsutton** [SimformSolutionsPvtLtd/flutter_calendar_view#436]
The monthview has 'onCellTap', dateview 'onDateTap', weekview 'onDateTap'.

These three methods should be consistently named.

onCellTap feels like the more evocative name as in all views I'm not click on a 'date' but rather a cell within the calendar which represents a particular moment in time, hence the word 'date' in these methods is misleading.

So I'm suggesting that the api should use:

onCellTap
onCellLongPressed
onCellDoubleTap

for each of the views.

This would also make exploring the api easier.  
I initially implemented the month view and then could find the equivalent api for week and day.

**Comment by bsutton** [comment]
there is also the questions of why the onCellTap provides a list of events and the onDateTap methods don't.

What is the purpose of passing the existing events for the onCellTap api?
Why don't the onDateTap have the same events.

I would argue (without knowledge of other requirements) that there doesn't appear to be any reason to pass the events to the onTap method.  I feels like there should be a method to query the list of events for a date/time range that you can query at any point in time.

**Comment by shubham-jitiya-simform** [comment]
Hi @bsutton,
- `onCellTap` is used in the month view because it has grids and represents actual cells of the grid view. Each cell can have a list of events. You will get the date on which the user has tapped and the list of events on that day, if any.
- This can be useful for displaying event details or making decisions based on the events associated with that cell.
- For `onDateTap` in the week view, it will provide the time span on which the user has tapped, and events can have various end times, unlike the month view where events typically end on the same day. Similar for day view.

**Comment by bsutton** [comment]
I'm not certain you have actually described different things - the three
api's are essentially identical in concept.

>  month view because it has grids and represents actual cells
the month's relation to a grid view is really not material to the api and
probably problematic to the api's evolution e.g. you might want to provide
an alternate view which doesn't use a grid.
What is key is that the user has click a 'time period' and may want events
that are related to that time period.

> date on which the user has tapped and the list of events on that day
I would argue that each view should either return a list events that
overlap the region clicked or probably better not pass any events but allow
a user to query the events in a date/time range.

>  it will provide the time span on which the user has tapped
both the onCell and onDate essentially provide a time span that the user
has tapped.

> and events can have various end times
This is not particularly relevant to a users view of the api.  For a
multi-day event the month view can also have events with various end times.
In all cases the user may want to find all events that overlap that period,
including multi-day events.


I don't think you have raised a valid argument why these api have different
names and unifying them would make using the api easier whilst detaching
the api from the UI representation allows for future evolution of ui.

The current implementation is non-obvious and somewhat clumsy to use.
