### ISSUE TITLE
Change beginning of week in MonthView

### ISSUE THREAD

**Issue by awatson32** [SimformSolutionsPvtLtd/flutter_calendar_view#46]
Is it possible to have the first day of the week in MonthView be Sunday? How can I accomplish this?
<img width="493" alt="Screen Shot 2022-03-02 at 4 27 04 PM" src="https://user-images.githubusercontent.com/7787006/156460601-7a436b9b-c454-4de1-aa7e-8c1cbc35c849.png">

**Comment by vradchuk** [comment]
The same for VewwView. Is there a way to do it?
