### ISSUE TITLE
WeekView header date is different from the calendar view

### ISSUE THREAD

**Issue by vradchuk** [SimformSolutionsPvtLtd/flutter_calendar_view#48]
Looks like the WeekView header date is one week after the calendar view.
Is it expected behavior?

For example https://drive.google.com/file/d/1G0RH_Khm8PFCoTcHXyZKrmso4goOd3Tx/view?usp=sharing

**Comment by PRBaraiya** [comment]
Hello @vradchuk , I am not able to reproduce this issue. If possible, please share the code snippet that can produce this issue.

**Comment by vradchuk** [comment]
Hello, @PRBaraiya 
You can see it even on your example here: https://simformsolutionspvtltd.github.io/flutter_calendar_view/#/
Just select Week and observer calendar header and weekdays.

**Comment by PRBaraiya** [comment]
@vradchuk  Here, is what I see in my browser,
![Screenshot 2022-03-08 at 10 15 27 AM](https://user-images.githubusercontent.com/75968805/157167949-54c1a9dc-3758-4ead-a27c-39ce24ba0748.png)
.

Is there any steps that you performed to produce this issue? If so please share it here.

**Comment by PRBaraiya** [comment]
Ok, got the problem. Its setting one week ahead of whatever is selected while changing the week programmatically using jumpToWeek method. @vradchuk Am I correct? or there is something I'm missing?
