### ISSUE TITLE
Unbounded height constraints when put as part of Sliver

### ISSUE THREAD

**Issue by kkondarev** [SimformSolutionsPvtLtd/flutter_calendar_view#49]
Hi, I am trying to add the DayView in a Sliver, but whatever I try, I get one or other variation of "unbounded height constraints".
Code and exception below:

`Widget getCalendarView() { 

    return SliverList(
      delegate: SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          return SingleChildScrollView(
            child: DayView(
              controller: EventController(),
            ),
          );
        },
        childCount: 1,
      ),
    );
  }`

I was looking for a way to declare that I want to shrink-wrap the DayView, but found none... any ideas? 

Thanks and best regards
Kras

Exception:
The following assertion was thrown during performLayout():
RenderFlex children have non-zero flex but incoming height constraints are unbounded.

When a column is in a parent that does not provide a finite height constraint, for example if it is in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining space in the vertical direction.
These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child cannot simultaneously expand to fit its parent.

Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible children (using Flexible rather than Expanded). This will allow the flexible children to size themselves to less than the infinite remaining space they would otherwise be forced to take, and then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum constraints provided by the parent.

If this message did not help you determine the problem, consider using debugDumpRenderTree():
  [https://flutter.dev/debugging/#rendering-layer]()
  [http://api.flutter.dev/flutter/rendering/debugDumpRenderTree.html]()
The affected RenderFlex is: RenderFlex#408be relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
    size: MISSING
    direction: vertical
    mainAxisAlignment: start
    mainAxisSize: min
    crossAxisAlignment: start
    textDirection: ltr
    verticalDirection: down
    child 1: RenderDecoratedBox#419af NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
        constraints: MISSING
        size: MISSING
        decoration: BoxDecoration
            color: Color(0xffdcf0ff)
        configuration: ImageConfiguration(bundle: PlatformAssetBundle#b0938(), devicePixelRatio: 2.6, locale: en_US, textDirection: TextDirection.ltr, platform: android)
        child: RenderClipPath#eb64c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: <none>
            constraints: MISSING
            size: MISSING
            child: RenderFlex#84689 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                direction: horizontal
                mainAxisAlignment: spaceBetween
                mainAxisSize: max
                crossAxisAlignment: center
                needs compositing
                parentData: <none>
                constraints: MISSING
                size: MISSING
                usefulness ratio: no metrics collected yet (never painted)
                child: _RenderScrollSemantics#2aff5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    semantic boundary
                    size: MISSING
The creator information is set to: Column ← DecoratedBox ← SizedBox ← MediaQuery ← Padding ← SafeArea ← DayView<dynamic> ← _SingleChildViewport ← IgnorePointer-[GlobalKey#33e91] ← Semantics ← Listener ← _GestureSemantics ← ⋯

**Comment by ujas-m-simformsolutions** [comment]
Hello @kkondarev, You are using a scollable widget (**DayView**), inside scrollable widget (**SingleChildScrollView**), inside a sliver scollable (**SliverList**). That's why it's giving you unbounded height error and DayView is already scrollable so you don't have to wrap it with singlechildscrollview to make it scrollable.
 
So, First instead of using singlechildscrollview and sliverlist, use `SliverToBoxAdapter`. SliverToBoxAdapter takes a normal widget and it can be used as sliver. Or use `SliverFillRemaining` it also takes a normal widget and can be used as sliver.

**Comment by PRBaraiya** [comment]
@kkondarev I'm closing this issue for now. Feel free to reopen this issue if you are still facing it.
