### ISSUE TITLE
How to get click event, if no event is set?

### ISSUE THREAD

**Issue by CharanjeetRPOPS** [SimformSolutionsPvtLtd/flutter_calendar_view#50]
How can i get click event (with time) tapping on time area where i have no events scheduled at 3 am (attached below) ?

![Screenshot_1646919190](https://user-images.githubusercontent.com/36876618/157672598-326a39c2-6f48-4fe4-aa44-7b2389caa471.png)

**Comment by PRBaraiya** [comment]
@CharanjeetRPOPS  You can get long press event on that area by providing, `onDateLongPress` argument in `DateView`

As of now calendar view does not supports single click event outside of event tile.

**Comment by francescovgg** [comment]
Please have a look at PR #105

**Comment by faiyaz-shaikh** [comment]
Added in 1.0.1 PR #128
