### ISSUE TITLE
can change first day of week?

### ISSUE THREAD

**Issue by AlphaCodeProgrammer** [SimformSolutionsPvtLtd/flutter_calendar_view#60]

**Comment by AlphaCodeProgrammer** [comment]
i want to change first day of week to Saturday how can i do that?

**Comment by AlphaCodeProgrammer** [comment]
> [heronlyj@6ff7614](https://github.com/heronlyj/flutter_calendar_view/commit/6ff7614fecff5b4778354a5c67544a96d2584fd4)

thank you bro it's amazing , this calendar can be use for jalali Dates?
THANK YOU

**Comment by PRBaraiya** [comment]
Fixed in PR [#72](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/pull/72)
