### ISSUE TITLE
[BUG] Duplicate item in cells while adding events in the same session

### ISSUE THREAD

**Issue by Nico3652** [SimformSolutionsPvtLtd/flutter_calendar_view#61]
First thanks for the package. 

I faced a duplicate issue on my project and then I tested your code and it happen for 100%. 

USE CASE : I simply add events on a common date and the last event is duplicated in cell : 

<img width="415" alt="Capture d’écran 2022-04-16 à 15 34 05" src="https://user-images.githubusercontent.com/50270977/163677047-71676583-9626-4613-8b6c-e9fd2c63b348.png">

The duplicate is visible only when a previous event is already present in the cell -> Bike task is alone only on the 20 and Swim only on 22-23  
More events I add more it's duplicated x2, x3...

I checked current issue but nothing found related to this,
How can we solve this ?

**Comment by DevuSeeroo** [comment]
Is this solved?

**Comment by loreminekarthik** [comment]
we are also experiencing the same issue. our requirement is to load all events in a month  at once.
we bring to load and remove the hall months data and reload the next month data by detecting swipe. 
it is showing duplicate entry's when we  do this.

**Comment by ParthBaraiya** [comment]
Hi! @Nico3652 @loreminekarthik  @DevuSeeroo, If possible, can any one of you share an example of Event data you are adding in Event Controller.
