### ISSUE TITLE
support Jalali Date

### ISSUE THREAD

**Issue by AlphaCodeProgrammer** [SimformSolutionsPvtLtd/flutter_calendar_view#64]
i can give you useful data for add Jalali date to calendar you can use this package for convert Gregorian to Jalali date [https://pub.dev/packages/shamsi_date](https://github.com/syncfusion/flutter-examples/issues/url)
and this package for convert English numbers to Persian numbers [https://pub.dev/packages/shamsi_date]
and then make this calendar AMAZING!

**Comment by ParthBaraiya** [comment]
Thank you very much @AlphaCodeProgrammer for this suggestion. But we are not planning to add support for jalali dates for now.  So, I'm closing this issue for time being. We will reopen this issue in future if we consider adding support for jalali dates.
