### ISSUE TITLE
How to change Day, Week, Month View with custom headerBuider

### ISSUE THREAD

**Issue by NitinSojitra** [SimformSolutionsPvtLtd/flutter_calendar_view#83]
I want to change month view when I press the left and right arrow.
When I press left arrow, I want to see previous month view.
When I press right arrow, I want to see next month view.

![Screenshot 2022-07-28 at 4 03 01 PM](https://user-images.githubusercontent.com/107480344/181485170-8b0e2360-529c-4e05-9e13-f792d12bbd7d.png)

**Comment by PRBaraiya** [comment]
@NitinSojitra  Please review this README file for your queries.

https://pub.dev/packages/calendar_view#use-of-globalkey

**Comment by NitinSojitra** [comment]
Thanks.
