### ISSUE TITLE
Change amount of rows (height) of month view.

### ISSUE THREAD

**Issue by TomasWard1** [SimformSolutionsPvtLtd/flutter_calendar_view#95]
Hello! I have implemented a month view and the available space is not the full screen. Therefore, the month view contains six rows (weeks) which scroll up and down with the cells having a fixed height. I do not want this, I would prefer:
Setting an arbitrary height of the month view (for example using an expanded widget), and for the cells to adjust their heigh (aspect ratio) appropriately so there never is scrolling. Or the option to have only 5 weeks displayed, but still the height of the cells should fix neatly, without the need to scroll up or down the month view. Thanks!

**Comment by ParthBaraiya** [comment]
This will be implemented along with issue #141 .
